//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orvosirendelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Betegek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Betegek()
        {
            this.Idoponts = new HashSet<Idopont>();
        }
    
        public int BetegSK { get; set; }
        public string BetegNev { get; set; }
        public string SZIG { get; set; }
        public string TAJ { get; set; }
        public string Email { get; set; }
        public string Telefonszám { get; set; }
        public string Jelszo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Idopont> Idoponts { get; set; }
    }
}
