//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orvosirendelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database2Entities : DbContext
    {
        public Database2Entities()
            : base("name=Database2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Betegek> Betegeks { get; set; }
        public virtual DbSet<Ido> Idoes { get; set; }
        public virtual DbSet<Idopont> Idoponts { get; set; }
        public virtual DbSet<Orvosfajtak> Orvosfajtaks { get; set; }
        public virtual DbSet<Orvosok> Orvosoks { get; set; }
    }
}
